name: Go

on:
  push:
    branches: [ main, corecliapp ]
  pull_request:
    branches: [ main, corecliapp ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.14', '1.15', '1.16', '1.17']
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    steps:
    - uses: actions/checkout@v2

    - name: Use GO ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test GO ${{ matrix.go_version }}
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload to codecov
      run: bash <(curl -s https://codecov.io/bash)

